### ISSUE TITLE
solidjs start下无法使用,什么时候修复一下

### ISSUE THREAD

**Issue by muzidudu** [i18n-pro/solid#1]

**Comment by eyelly-wu** [comment]
@muzidudu 方便提供一下可复现的示例吗？在线的例如 codesandbox 或者GitHub代码库都可以

**Comment by muzidudu** [comment]
@eyelly-wu   [https://github.com/muzidudu/solid-i18n-bug](https://github.com/muzidudu/solid-i18n-bug) 代码上传过了

**Comment by eyelly-wu** [comment]
@muzidudu 问题已解决，需要将 `@i18n-pro/solid` 的版本升到 1.0.1，并且 root.tsx 的代码需要调整为类似下面的样子

主要是 `useI18n` 需要在 `I18nProvider` 包裹的子级才能正常使用，不能出现在同一级

```tsx
// @refresh reload
import { Suspense } from "solid-js";
import {
  A,
  Body,
  ErrorBoundary,
  FileRoutes,
  Head,
  Html,
  Meta,
  Routes,
  Scripts,
  Title,
} from "solid-start";
import "./root.css";
import { I18nProvider, useI18n } from '@i18n-pro/solid'
import i18nState from './i18n'

function Root() {
  const { t } = useI18n()
  return (
    <Html lang="en">
      <Head>
        <Title>SolidStart - Bare</Title>
        <Meta charset="utf-8" />
        <Meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Body>
        <Suspense>
          <ErrorBoundary>
          {t('hello world')}
            <A href="/">Index</A>
            <A href="/about">About</A>
            <Routes>
              <FileRoutes />
            </Routes>
          </ErrorBoundary>
        </Suspense>
        <Scripts />
      </Body>
    </Html>
  );
}

export default function (){
  return (
    <I18nProvider {...i18nState}>
      <Root />
    </I18nProvider>
  )
}
```

**Comment by muzidudu** [comment]
@eyelly-wu  [codesanbox](https://codesandbox.io/p/github/muzidudu/solid-i18n-bug/main?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clo82gzyk00073t6gt7g2ooky%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clo82gzyk00033t6g9dvh08c1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clo82gzyk00053t6gfs5uflaw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clo82gzyk00063t6g82ibu7p0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clo82gzyk00033t6g9dvh08c1%2522%253A%257B%2522id%2522%253A%2522clo82gzyk00033t6g9dvh08c1%2522%252C%2522activeTabId%2522%253A%2522clo82l1je003y3t6ge8ytlk3m%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo82gzyk00023t6g5zirmx32%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Froot.tsx%2522%252C%2522id%2522%253A%2522clo82l1je003y3t6ge8ytlk3m%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clo82gzyk00063t6g82ibu7p0%2522%253A%257B%2522id%2522%253A%2522clo82gzyk00063t6g82ibu7p0%2522%252C%2522activeTabId%2522%253A%2522clo9g81dl003g3t6gktkgbd0r%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clo9g81dl003g3t6gktkgbd0r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clo82gzyk00053t6gfs5uflaw%2522%253A%257B%2522id%2522%253A%2522clo82gzyk00053t6gfs5uflaw%2522%252C%2522activeTabId%2522%253A%2522clo9g5mvn00733t6gd8ip856y%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo82gzyk00043t6g21ittozm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clo82l8ha0016eeg3bv95gvay%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clo82i1nn00af3t6g4rtbgaye%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clo9g5mvn00733t6gd8ip856y%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 可以翻译了,但是报错提示水合错误

```
Error: Hydration Mismatch. Unable to find DOM nodes for hydration key: 0-0-0-0-0-0-0-0-0-0-0-1-0-0-0-0-1-0
    at getNextElement (dev.js:735:13)
    at components.jsx:106:5
    at A (components.jsx:111:57)
    at dev.js:620:16
    at untrack (dev.js:503:12)
    at Object.fn (dev.js:616:7)
    at runComputation (dev.js:781:22)
    at updateComputation (dev.js:760:3)
    at devComponent (dev.js:631:3)
    at createComponent (dev.js:1378:17)
dev.js:735  Uncaught Error: Hydration Mismatch. Unable to find DOM nodes for hydration key: 1-0-0
    at getNextElement (dev.js:735:13)
    at ErrorBoundary.tsx:32:3
    at ErrorMessage (ErrorBoundary.tsx:59:79)
    at dev.js:620:16
    at untrack (dev.js:503:12)
    at Object.fn (dev.js:616:7)
    at runComputation (dev.js:781:22)
    at updateComputation (dev.js:760:3)
    at devComponent (dev.js:631:3)
    at createComponent (dev.js:1378:17)
```

**Comment by eyelly-wu** [comment]
@muzidudu 找到原因了，我猜测你创建项目的时候是开启了 `Server Side Rendering` 对吧？
<img width="470" alt="image" src="https://github.com/i18n-pro/solid/assets/24505069/a2927540-9755-4dc5-92e2-8d921ebfcd80">
目前从官方的文档中，暂时还不清楚应该怎么处理服务端渲染时状态如何处理

如果不开启 `Server Side Rendering` 创建的项目的话，就不会报上面的 `Uncaught Error: Hydration Mismatch. Unable to find DOM nodes for hydration key`  这个异常

可参考
1. [GitHub](https://github.com/i18n-pro/solid-start-demo)
2. [CodeSandbox](https://codesandbox.io/p/github/i18n-pro/solid-start-demo/main)

**Comment by muzidudu** [comment]
@eyelly-wu 好的,感谢你的回答
