### ISSUE TITLE
Do you plan to add in dynamic imports?

### ISSUE THREAD

**Issue by onx2** [i18n-pro/solid#2]
With the current approach all of the locales must be downloaded by the user, even if they will never use them. With large sites this can have a negative impact on performance. Would you consider allowing something like following API for dynamic imports?

```ts
export const i18nState = {
  namespace: "example",
  locale: "en",
  langs: {
    de: () => import("./locales/de.json"),
    es: () => import("./locales/es.json"),
  },
} as I18nState;
```

Currently all files are loaded:
<img width="583" alt="image" src="https://github.com/i18n-pro/solid/assets/23039725/236538dd-c3fd-4d65-87bc-3fea6e6e01d3">

**Comment by onx2** [comment]
My current workaround is totally fine but I just think it would be nice to natively support this.

**Workaround function**
```ts
import { I18nState } from "@i18n-pro/solid";

/**
 * Dynamically imports in a language and returns the setI18n options
 *
 * @async
 * @param {string} lang
 * @returns {unknown}
 */
export const getLang = async (
  lang: string
): Promise<Pick<I18nState, "locale" | "langs">> => {
  return {
    locale: lang,
    langs: {
      fr: (await (() => import(`./locales/${lang}.json`))()).default,
    },
  };
};

```

**Usage**
```tsx
<Button onClick={async () => setI18n(await getLang("es"))}>
  Spanish
</Button>
```

**Comment by onx2** [comment]
It would be nice to have it natively in the package as an acceptable config property but my workaround is fine too:

```ts
import { I18nState } from "@i18n-pro/solid";

/**
 * Dynamically imports in a language and returns the setI18n options
 *
 * @async
 * @param {string} lang
 * @returns {unknown}
 */
export const getLang = async (
  lang: string
): Promise<Pick<I18nState, "locale" | "langs">> => {
  return {
    locale: lang,
    langs: {
      [lang]: (await (() => import(`./locales/${lang}.json`))()).default,
    },
  };
};
```

**Usage**
```tsx
<Button onClick={async () => setI18n(await getLang("fr"))}>
  French
</Button>
```

**Comment by eyelly-wu** [comment]
@onx2 
Thank you for your feedback. Currently, there are no plans to support this feature (it may be considered in future major versions). The current design ensures that all APIs, including language switching, are synchronous. The `setI18n` function is designed to accept the target language and the corresponding language pack, meaning it's not mandatory to load all language packs at initialization. You can dynamically load language packs based on the scenario; however, the implementation of loading logic for language packs needs to be handled at the user level.

For further clarification, please refer to the following two examples:
- [Solid I18n Demo on CodeSandbox](https://codesandbox.io/p/github/i18n-pro/solid-demo/main?file=README.md)
- [Solid I18n Demo on StackBlitz](https://stackblitz.com/github/i18n-pro/solid-demo?file=README.md)

**Comment by onx2** [comment]
Thanks for the quick response. That solution is nice as well - I think I can close this as there are two options for handling this on the user side. Cheers!

**Comment by eyelly-wu** [comment]
> With the current approach all of the locales must be downloaded by the user, even if they will never use them. With large sites this can have a negative impact on performance. Would you consider allowing something like following API for dynamic imports?
> 
> export const i18nState = {
>   namespace: "example",
>   locale: "en",
>   langs: {
>     de: () => import("./locales/de.json"),
>     es: () => import("./locales/es.json"),
>   },
> } as I18nState;
> Currently all files are loaded: <img alt="image" width="583" src="https://private-user-images.githubusercontent.com/23039725/338359363-236538dd-c3fd-4d65-87bc-3fea6e6e01d3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTcxNTUyNDAsIm5iZiI6MTc1NzE1NDk0MCwicGF0aCI6Ii8yMzAzOTcyNS8zMzgzNTkzNjMtMjM2NTM4ZGQtYzNmZC00ZDY1LTg3YmMtM2ZlYTZlNmUwMWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTA2VDEwMzU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZjQzYzdkY2MzNjI3NjQ2N2MwMWFmOGNmZjdjODM3NmFmN2EyMjdjMTU0OTBhY2FiMmUwZWM5OTBjNmViYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WaHAbgfpD4Qa5OdLU2XVcwRvgV6VbYfS7jPD0gYd1UQ">

Hey bro, this feature has been supported since v2.0.0. Thanks for the inspiration!
